"""updated add votes table by auto generation

Revision ID: e4be544fdc3c
Revises: 4a85c8beac95
Create Date: 2023-02-14 13:28:37.967413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4be544fdc3c'
down_revision = '4a85c8beac95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
